from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(981, 637)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_9 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setStyleSheet(_fromUtf8("\n"
"color: rgb(0, 85, 255);"))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.packageDirectoryLineEdit = QtGui.QLineEdit(self.groupBox_9)
        self.packageDirectoryLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.packageDirectoryLineEdit.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.packageDirectoryLineEdit.setObjectName(_fromUtf8("packageDirectoryLineEdit"))
        self.horizontalLayout.addWidget(self.packageDirectoryLineEdit)
        self.packageDirectoryBrowseButton = QtGui.QPushButton(self.groupBox_9)
        self.packageDirectoryBrowseButton.setStyleSheet(_fromUtf8("color: rgb(255,255,255);\n"
"background-color: rgb(0, 85, 255);"))
        self.packageDirectoryBrowseButton.setObjectName(_fromUtf8("packageDirectoryBrowseButton"))
        self.horizontalLayout.addWidget(self.packageDirectoryBrowseButton)
        self.horizontalLayout_10.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.groupBox_9)
        self.bkmGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.bkmGroupBox.setStyleSheet(_fromUtf8("color:rgb(0, 85, 255);"))
        self.bkmGroupBox.setObjectName(_fromUtf8("bkmGroupBox"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.bkmGroupBox)
        self.horizontalLayout_19.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.packageFilesGroupBox = QtGui.QGroupBox(self.bkmGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.packageFilesGroupBox.sizePolicy().hasHeightForWidth())
        self.packageFilesGroupBox.setSizePolicy(sizePolicy)
        self.packageFilesGroupBox.setObjectName(_fromUtf8("packageFilesGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.packageFilesGroupBox)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.packageFilesTableWidget = QtGui.QTableWidget(self.packageFilesGroupBox)
        self.packageFilesTableWidget.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.packageFilesTableWidget.setObjectName(_fromUtf8("packageFilesTableWidget"))
        self.packageFilesTableWidget.setColumnCount(3)
        self.packageFilesTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.packageFilesTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.packageFilesTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.packageFilesTableWidget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_2.addWidget(self.packageFilesTableWidget)
        self.horizontalLayout_6.addWidget(self.packageFilesGroupBox)
        spacerItem = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.groupBox_3 = QtGui.QGroupBox(self.bkmGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setStyleSheet(_fromUtf8("color:rgb(0, 85, 255);"))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.launchBkmButton = QtGui.QPushButton(self.groupBox_3)
        self.launchBkmButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 0, 0);"))
        self.launchBkmButton.setObjectName(_fromUtf8("launchBkmButton"))
        self.verticalLayout_2.addWidget(self.launchBkmButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.viewBkmReportButton = QtGui.QPushButton(self.groupBox_3)
        self.viewBkmReportButton.setEnabled(True)
        self.viewBkmReportButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 170, 0);\n"
"color: rgb(0, 0, 0);"))
        self.viewBkmReportButton.setObjectName(_fromUtf8("viewBkmReportButton"))
        self.verticalLayout_2.addWidget(self.viewBkmReportButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addWidget(self.groupBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.preChecksGroupBox = QtGui.QGroupBox(self.bkmGroupBox)
        self.preChecksGroupBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.preChecksGroupBox.sizePolicy().hasHeightForWidth())
        self.preChecksGroupBox.setSizePolicy(sizePolicy)
        self.preChecksGroupBox.setSizeIncrement(QtCore.QSize(0, 3))
        self.preChecksGroupBox.setStyleSheet(_fromUtf8("color:rgb(0, 85, 255);"))
        self.preChecksGroupBox.setObjectName(_fromUtf8("preChecksGroupBox"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.preChecksGroupBox)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.checksGroupBox = QtGui.QGroupBox(self.preChecksGroupBox)
        self.checksGroupBox.setObjectName(_fromUtf8("checksGroupBox"))
        self.horizontalLayout_5.addWidget(self.checksGroupBox)
        self.verticalLayout_4.addWidget(self.preChecksGroupBox)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.colorTemplateGroupBox = QtGui.QGroupBox(self.bkmGroupBox)
        self.colorTemplateGroupBox.setEnabled(False)
        self.colorTemplateGroupBox.setObjectName(_fromUtf8("colorTemplateGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.colorTemplateGroupBox)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_9 = QtGui.QLabel(self.colorTemplateGroupBox)
        self.label_9.setMinimumSize(QtCore.QSize(30, 0))
        self.label_9.setStyleSheet(_fromUtf8("background-color:rgb(217, 0, 0);"))
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_6.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.colorTemplateGroupBox)
        self.label_10.setStyleSheet(_fromUtf8("background-color:rgb(0, 170, 0);"))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_6.addWidget(self.label_10)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_11 = QtGui.QLabel(self.colorTemplateGroupBox)
        self.label_11.setStyleSheet(_fromUtf8("color:rgb(0, 0, 0);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_9.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.colorTemplateGroupBox)
        self.label_12.setStyleSheet(_fromUtf8("color:rgb(0, 0, 0);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_9.addWidget(self.label_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_13 = QtGui.QLabel(self.colorTemplateGroupBox)
        self.label_13.setEnabled(False)
        self.label_13.setMinimumSize(QtCore.QSize(30, 0))
        self.label_13.setStyleSheet(_fromUtf8("background-color:rgb(250, 167, 0);"))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_10.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.colorTemplateGroupBox)
        self.label_14.setStyleSheet(_fromUtf8("background-color:rgb(126, 126, 94);"))
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_10.addWidget(self.label_14)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_15 = QtGui.QLabel(self.colorTemplateGroupBox)
        self.label_15.setStyleSheet(_fromUtf8("color:rgb(0, 0, 0);"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_11.addWidget(self.label_15)
        self.label_16 = QtGui.QLabel(self.colorTemplateGroupBox)
        self.label_16.setStyleSheet(_fromUtf8("color:rgb(0, 0, 0);"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_11.addWidget(self.label_16)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8.addWidget(self.colorTemplateGroupBox)
        spacerItem2 = QtGui.QSpacerItem(100, 13, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.releaseNotesGroupBox = QtGui.QGroupBox(self.bkmGroupBox)
        self.releaseNotesGroupBox.setObjectName(_fromUtf8("releaseNotesGroupBox"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.releaseNotesGroupBox)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.openReleaseNotesButtoon = QtGui.QPushButton(self.releaseNotesGroupBox)
        self.openReleaseNotesButtoon.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 170, 0);"))
        self.openReleaseNotesButtoon.setObjectName(_fromUtf8("openReleaseNotesButtoon"))
        self.horizontalLayout_7.addWidget(self.openReleaseNotesButtoon)
        self.horizontalLayout_8.addWidget(self.releaseNotesGroupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_19.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addWidget(self.bkmGroupBox)
        self.QuitBkmButton = QtGui.QPushButton(self.centralwidget)
        self.QuitBkmButton.setObjectName(_fromUtf8("QuitBkmButton"))
        self.verticalLayout_5.addWidget(self.QuitBkmButton)
        self.verticalLayout_19.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BKM_GUI", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Choose your Package Directory", None))
        self.packageDirectoryBrowseButton.setText(_translate("MainWindow", "Browse", None))
        self.bkmGroupBox.setTitle(_translate("MainWindow", "BKM", None))
        self.packageFilesGroupBox.setTitle(_translate("MainWindow", "Package Files", None))
        item = self.packageFilesTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Script", None))
        item = self.packageFilesTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Step", None))
        item = self.packageFilesTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Files", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Execute and View", None))
        self.launchBkmButton.setText(_translate("MainWindow", "Launch BKM", None))
        self.viewBkmReportButton.setText(_translate("MainWindow", "View BKM Report", None))
        self.preChecksGroupBox.setTitle(_translate("MainWindow", "BKM/Pre Checks", None))
        self.checksGroupBox.setTitle(_translate("MainWindow", "Checks", None))
        self.colorTemplateGroupBox.setTitle(_translate("MainWindow", "Color Template", None))
        self.label_11.setText(_translate("MainWindow", "FAIL(Mandatory Checks)", None))
        self.label_12.setText(_translate("MainWindow", "PASS(Mandatory/Optional Checks)", None))
        self.label_15.setText(_translate("MainWindow", "FAIL(Optional Checks", None))
        self.label_16.setText(_translate("MainWindow", "Not applicable Checks", None))
        self.releaseNotesGroupBox.setTitle(_translate("MainWindow", "Release Notes", None))
        self.openReleaseNotesButtoon.setText(_translate("MainWindow", "Open Release Notes", None))
        self.QuitBkmButton.setText(_translate("MainWindow", "Quit BKM", None))



if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


